# Generated by Django 4.1.2 on 2022-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('cpu', models.SmallIntegerField(verbose_name='central processing unit')),
                ('ram', models.SmallIntegerField(verbose_name='random access memory')),
                ('hdd', models.IntegerField(verbose_name='hard disk drive')),
                ('status', models.SmallIntegerField(choices=[(0, 'blocked'), (1, 'started'), (2, 'stopped')], db_index=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'virtual dedicated server',
                'verbose_name_plural': 'virtual dedicated servers',
            },
        ),
    ]
